GET http://localhost:3000/user/getusers

###
GET http://localhost:3000/user/getuser/saiprudvish

###
POST http://localhost:3000/user/createuser
Content-Type: application/json

{
    "username":"saiprudvish",
    "password":"sai_7",
    "email":"prudvish7@gmail.com",
    "city":"karimnagar",
    "age":20
}

###

PUT http://localhost:3000/user/updateuser/saiprudvish
Content-Type: application/json

{
      "username":"saiprudvish",
    "email":"saiprudvish7@gmail.com",
    "city":"karimnagar",
    "age":19
}
###

DELETE  http://localhost:3000/user/deleteuser/saiprudvish

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"saiprudvish",
    "password":"sai_7"
}