GET http://localhost:3000/user/getusers

###
GET http://localhost:3000/user/getuser/prudvish

###
POST http://localhost:3000/user/createuser
Content-Type: application/json

{
    "username":"prudvish",
    "email":"prudvish7@gmail.com",
    "city":"karimnagar",
    "age":20
}

###

PUT http://localhost:3000/user/updateuser/prudvish
Content-Type: application/json

{
      "username":"prudvish",
    "email":"saiprudvish7@gmail.com",
    "city":"karimnagar",
    "age":19
}